### ISSUE TITLE
New HLTV

### ISSUE THREAD

**Issue by andrewda** [Nols1000/hltv-scorebot#3]
With the new HLTV, the scorebot has had a few changes. There could also have been some changes to the backend, I'll try and look into that and see if anything has changed.

Crossed-out dead players:
![b615291186e67855b3752ee4cde41983](https://cloud.githubusercontent.com/assets/10191084/9310274/b1b0462c-44c3-11e5-8c10-40fd23156a92.png)

Current score after round over:
![0b137668ebccfcf4ba26d645aaa1dd32](https://cloud.githubusercontent.com/assets/10191084/9310279/b56cb7dc-44c3-11e5-94fb-60a6e5d7dc79.png)

**Comment by Nols1000** [comment]
HLTV Scorebot provides much more information now. I'll work on this.

New Scorebot:
- Event overhaul
- More log deth

**Comment by Nols1000** [comment]
Version 2.0 should contain all changes.
